### PR TITLE
fix C++20 compliance with application of upstream PR 965

### PR DESCRIPTION
**Pull request by mikehardy**
These symbols are no longer valid on macOS and will fail builds if the `NDEBUG` symbol is !defined, as it is now in default build settings for all react-native projects since release of react-native 0.76

This same change was applied upstream but never released, and it appears it has not been applied here

https://github.com/google/leveldb/pull/965#issuecomment-2436371816

See: https://github.com/invertase/react-native-firebase/issues/8082#issuecomment-2436363510

It would be fantastic to get a leveldb release with this fix, that firebase-ios-sdk adopted, so react-native-firebase was compatible with firebase-ios-sdk out of the box again with react-native 0.76

Thanks!

### CODE REVIEW

**Review by andrewheard — APPROVED** [review]
LGTM. This seems like a safe change regardless of what C++ Language Dialect is used for Firestore (based on manual testing and looking at the header in libc++).
- If compiling for C++17, or older, then `std::memory_order_relaxed` refers to `memory_order_relaxed` in the `memory_order` enum.
- If compiling for C++20, or newer, then `std::memory_order_relaxed` refers to `relaxed` in the new `memory_order` enum **class**; this is implemented with a `memory_order_relaxed` constexpr:
  - `inline constexpr auto memory_order_relaxed = memory_order::relaxed;`
  - I'm guessing they did this for backwards compatibility.

Also, thanks @mikehardy!

**Comment by paulb777** [comment]
Thanks @mikehardy! We're going to test overnight and if all goes well, we'll publish 1.22.6 tomorrow.

**Comment by AngeloAvv** [comment]
I'm experiencing the same problem with a Flutter build. Shall I report this problem somewhere? If yes, where's the best place to do it? Thanks!

```
fvm flutter build ios -t lib/main.dart --release --no-codesign --build-number $CI_PIPELINE_IID
Downloading ios tools...                                        
Downloading ios-profile tools...                                
Downloading ios-release tools...                                
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building xxx for device (ios-release)...
Running pod install...                                          
Running Xcode build...                                          
Xcode build done.                                           46.2s
Failed to build iOS app
Semantic Issue (Xcode): No member named 'memory_order_relaxed' in 'std::memory_order'; did you mean 'std::memory_order_relaxed'?
/Users/angeloavv/builds/h5vqU3qv/0/flutter/clients/xxx/ios/Pods/leveldb-library/util/env_posix.cc:839:33
Semantic Issue (Xcode): No member named 'memory_order_relaxed' in 'std::memory_order'; did you mean 'std::memory_order_relaxed'?
/Users/angeloavv/builds/h5vqU3qv/0/flutter/clients/xxx/ios/Pods/leveldb-library/util/env_posix.cc:856:34
Encountered error while building for device.
```

**Comment by mikehardy** [comment]
@AngeloAvv I believe this will resolve for you with these sets of steps and no further issues created:
1- wait for notice that 1.22.6 version of leveldb-library is published (using github web UI to "watch" this repository, for "releases" should allow you to receive notice)
2- remove ios/Podfile.lock, run `pod repo update`, then cd `ios` folder run `pod install` and I *think* the new release will automatically install [based on the `~>` style cocoapods dependency](https://github.com/search?q=repo%3Afirebase%2Ffirebase-ios-sdk+leveldb-library+language%3ARuby&type=code&l=Ruby) specified in firebase-ios-sdk which should allow the new point release to match the version constraint
3- build as normal, should succeed

**Comment by paulb777** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  leveldb-library (1.22.6) successfully published
 📅  October 29th, 08:14
 🌎  https://cocoapods.org/pods/leveldb-library
 👍  Tell your friends!
--------------------------------------------------------------------------------

**Comment by AngeloAvv** [comment]
I don't know if it's related, but it's getting worse and worse.

```
fvm flutter build ios -t lib/main.dart --release --no-codesign --build-number $CI_PIPELINE_IID
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building xxx for device (ios-release)...
Running pod install...                                          
Running Xcode build...                                          
Xcode build done.                                           1016.5s
Failed to build iOS app
Error (Xcode): Undefined symbol: absl::lts_20240116::CHexEscape(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::FormatTime(absl::lts_20240116::string_view, absl::lts_20240116::Time, absl::lts_20240116::TimeZone)
Error (Xcode): Undefined symbol: absl::lts_20240116::SimpleAtof(absl::lts_20240116::string_view, float*)
Error (Xcode): Undefined symbol: absl::lts_20240116::Base64Escape(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::UnknownError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::log_internal::LogMessage::AtLocation(absl::lts_20240116::string_view, int)
Error (Xcode): Undefined symbol: void absl::lts_20240116::log_internal::LogMessage::CopyToEncodedBuffer<(absl::lts_20240116::log_internal::LogMessage::StringType)0>(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: void absl::lts_20240116::log_internal::LogMessage::CopyToEncodedBuffer<(absl::lts_20240116::log_internal::LogMessage::StringType)1>(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::log_internal::LogMessage::operator<<(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::log_internal::PrependVModule(absl::lts_20240116::string_view, int)
Error (Xcode): Undefined symbol: absl::lts_20240116::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::InternalError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::NotFoundError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::StrReplaceAll(absl::lts_20240116::string_view, std::initializer_list<std::__1::pair<absl::lts_20240116::string_view, absl::lts_20240116::string_view>>)
Error (Xcode): Undefined symbol: absl::lts_20240116::Base64Unescape(absl::lts_20240116::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)
Error (Xcode): Undefined symbol: absl::lts_[202](https://gitlab.mylittlesuite.com/flutter/clients/xxx/-/jobs/78802#L202)40116::CancelledError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::flags_internal::AbslParseFlag(absl::lts_20240116::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)
Error (Xcode): Undefined symbol: absl::lts_20240116::flags_internal::AbslParseFlag(absl::lts_20240116::string_view, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)
Error (Xcode): Undefined symbol: absl::lts_20240116::flags_internal::AbslParseFlag(absl::lts_20240116::string_view, bool*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)
Error (Xcode): Undefined symbol: absl::lts_20240116::flags_internal::AbslParseFlag(absl::lts_20240116::string_view, int*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)
Error (Xcode): Undefined symbol: absl::lts_20240116::flags_internal::AbslUnparseFlag(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::status_internal::StatusRep::SetPayload(absl::lts_20240116::string_view, absl::lts_20240116::Cord)
Error (Xcode): Undefined symbol: absl::lts_20240116::BytesToHexString(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::EqualsIgnoreCase(absl::lts_20240116::string_view, absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::UnavailableError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::numbers_internal::safe_strto32_base(absl::lts_20240116::string_view, int*, int)
Error (Xcode): Undefined symbol: absl::lts_20240116::numbers_internal::safe_strto64_base(absl::lts_20240116::string_view, long long*, int)
Error (Xcode): Undefined symbol: absl::lts_20240116::numbers_internal::safe_strtou32_base(absl::lts_20240116::string_view, unsigned int*, int)
Error (Xcode): Undefined symbol: absl::lts_20240116::numbers_internal::safe_strtou64_base(absl::lts_20240116::string_view, unsigned long long*, int)
Error (Xcode): Undefined symbol: absl::lts_20240116::strings_internal::AppendPieces(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::initializer_list<absl::lts_20240116::string_view>)
Error (Xcode): Undefined symbol: absl::lts_20240116::strings_internal::StringifySink::Append(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::strings_internal::CatPieces(std::initializer_list<absl::lts_20240116::string_view>)
Error (Xcode): Undefined symbol: absl::lts_20240116::variant_internal::ThrowBadVariantAccess()
Error (Xcode): Undefined symbol: absl::lts_20240116::EndsWithIgnoreCase(absl::lts_20240116::string_view, absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::UnimplementedError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::WebSafeBase64Escape(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: bool absl::lts_20240116::str_format_internal::FormatArgImpl::Dispatch<absl::lts_20240116::string_view>(absl::lts_20240116::str_format_internal::FormatArgImpl::Data, absl::lts_20240116::str_format_internal::FormatConversionSpecImpl, void*)
Error (Xcode): Undefined symbol: absl::lts_20240116::InvalidArgumentError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::StartsWithIgnoreCase(absl::lts_20240116::string_view, absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::UnauthenticatedError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::DeadlineExceededError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::PermissionDeniedError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::WebSafeBase64Unescape(absl::lts_20240116::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)
Error (Xcode): Undefined symbol: absl::lts_20240116::ResourceExhaustedError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::FailedPreconditionError(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::Cord::GetFlatAux(absl::lts_20240116::cord_internal::CordRep*, absl::lts_20240116::string_view*)
Error (Xcode): Undefined symbol: absl::lts_20240116::Cord::InlineRep::AppendArray(absl::lts_20240116::string_view, absl::lts_20240116::cord_internal::CordzUpdateTracker::MethodIdentifier)
Error (Xcode): Undefined symbol: absl::lts_20240116::Cord::Cord(absl::lts_20240116::string_view, absl::lts_20240116::cord_internal::CordzUpdateTracker::MethodIdentifier)
Error (Xcode): Undefined symbol: absl::lts_20240116::Status::Status(absl::lts_20240116::StatusCode, absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::CEscape(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::ByString::ByString(absl::lts_20240116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::CUnescape(absl::lts_20240116::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)
Error (Xcode): Undefined symbol: absl::lts_20240116::ParseTime(absl::lts_20240116::string_view, absl::lts_20240116::string_view, absl::lts_20240116::Time*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)
Error (Xcode): Undefined symbol: absl::lts_20240116::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, absl::lts_20[240](https://gitlab.mylittlesuite.com/flutter/clients/xxx/-/jobs/78802#L240)116::string_view)
Error (Xcode): Undefined symbol: absl::lts_20240116::string_view::find_first_of(absl::lts_20240116::string_view, unsigned long) const
Error (Xcode): Undefined symbol: absl::lts_20240116::string_view::find(absl::lts_20240116::string_view, unsigned long) const
Error (Xcode): Undefined symbol: absl::lts_20240116::string_view::find(char, unsigned long) const
Error (Xcode): Undefined symbol: absl::lts_20240116::string_view::rfind(char, unsigned long) const
Error (Xcode): Undefined symbol: absl::lts_20240116::status_internal::StatusRep::GetPayload(absl::lts_20240116::string_view) const
Error (Xcode): Undefined symbol: absl::lts_20240116::status_internal::StatusRep::ForEachPayload(absl::lts_20240116::FunctionRef<void (absl::lts_20240116::string_view, absl::lts_20240116::Cord const&)>) const
Error (Xcode): Undefined symbol: absl::lts_20240116::ByChar::Find(absl::lts_20240116::string_view, unsigned long) const
Error (Xcode): Undefined symbol: absl::lts_20240116::ByString::Find(absl::lts_20240116::string_view, unsigned long) const
Encountered error while building for device.
```

**Comment by mikehardy** [comment]
Confirmed a fresh pod install (that is, after removing any existing Podfile.lock) installs the latest version:

> Installing leveldb-library (1.22.6)

...and it builds perfectly for me out of the box, thanks!

**Comment by mikehardy** [comment]
@AngeloAvv I will guess you are now using cocoapods 1.16.0 and/or xcodeproj 1.26.0, newly released.
They have some problems for some reason and I can't build with them either, same error
Use cocoapods 1.15.2 and xcodeproj 1.25.0 gems to build
reference https://github.com/facebook/react-native/pull/47237

**Comment by mikehardy** [comment]
Hopefully everyone has moved to the latest release on this one - I had very-temporarily directed people to the commit on my branch as a workaround but I do not want anything like that to be long-lived so with apologies to anyone affected, I am deleting my branch now

Everyone should be relying on the official release now

**Pull request merged**
