### PR TITLE
[leveldb] Remove unneeded GoogleTest submodule

### PR DESCRIPTION
**Pull request by ncooke3**

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
Usages in *_test.cc, but this should be fine for Firebase.

LGTM on green

**Comment by ncooke3** [comment]
@paulb777 , I was going to ask about that. Should those be removed? there are also some usages in the Makefile infra?

**Comment by paulb777** [comment]
I think we should keep them to minimize differences with the parent repo.

**Comment by ncooke3** [comment]
> minimize differences with the parent repo.

SGTM, I like that reasoning!

**Comment by ncooke3** [comment]
So I double-checked and this doesn't look to have implications on CocoaPods since the test code doesn't look to be pulled down into the workspace. This could still help decrease the pod install time. Do you feel we should do a CocoaPods and SPM release?

**Comment by ncooke3** [comment]
I think we might as well to keep them in sync since this repo is rarely updated.

**Pull request merged**
